web_flask/auth.py
from models import storage
from models.user import User
from models.family import Family
from flask import Blueprint, render_template, url_for,request, flash, redirect
from flask_login import logout_user, login_user
# import string, random

import hashlib
import re

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        # Process the form submission
        email = request.form.get('email')
        password = request.form.get('password')
        hash_password = hashlib.md5(password.encode()).hexdigest()

        user = storage.find_user_by_email(email)
        if user:
            if hash_password == user.password:
                login_user(user, remember=True)
                return redirect(url_for('views.dashboard'))
            else: 
                flash('Incorrect Password, try again', category='error')
        else:
            flash('User with this email does not exist', category='error')

    return render_template('auth/login.html') 

# REGISTER ROUTE FUNCTIONALITY
@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':

        user_data = {
            "firstname": request.form.get('firstname'),
            "lastname": request.form.get('lastname'),
            "username": request.form.get('username'),
            "password": request.form.get('password'),
            "confirm_pass": request.form.get('confirm_pass'),
            "email": request.form.get('email'),
            "address": request.form.get('address'),
            "zipcode": request.form.get('zipcode'),
            "country": request.form.get('country'),
            "state": request.form.get('state'),
            "birth_month": request.form.get('birth_month'),
            "birth_day": request.form.get('birth_day'),
            "t_c": request.form.get('t_c')
        }
        existing_user = storage.find_user_by_email(user_data['email'])
        if existing_user:
            flash('Email already exists. Please login.', category='error')
        elif len(user_data['firstname']) < 2:
            flash('First Name must be greater than 1 character', category='error')
        elif len(user_data['lastname']) < 2:
            flash('Last Name must be greater than 1 character', category='error')
        elif user_data['password'] != user_data['confirm_pass']:
            flash('Passwords do not match', category='error')
        elif len(user_data['password']) < 6:
            flash('Password must be at least 6 characters long', category='error')
        elif not re.match(r"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$", user_data['email']):
            flash('Invalid email address', category='error')
        elif len(user_data['zipcode']) > 5:
            flash('Invalid zipcode', category='error')
        elif 't_c' not in user_data:
            flash('You must accept the terms and conditions to register', category='error')
        # elif any(not user_data[field] for field in ['firstname', 'lastname', 'password', 'confirm_pass', 'email', 'address', 'zipcode', 'country', 'state', 'birth_month', 'birth_day']):
        #     flash('All fields are required', category='error')
        else:
            family_option = request.form.get('family_option') == 'create'  # Assuming you have a checkbox in your form
            if family_option:

                family_name = request.form.get('family_name')  # Get the family name from the form
                if not family_name:
                    flash('Family name is required to create a new family', category='error')
                    return render_template('auth/register.html', user_data=user_data)  # Display the registration form again
                if all(user_data[field] for field in ['firstname', 'lastname', 'password', 'confirm_pass', 'email', 'address', 'zipcode', 'country', 'state', 'birth_month', 'birth_day']):
                    # All checks passed, proceed with registration
                    birthday = f"{user_data['birth_month']}/{user_data['birth_day']}"
                    new_user = User(
                        firstname=user_data['firstname'],
                        lastname=user_data['lastname'],
                        username=user_data['username'],
                        password=user_data['password'],
                        email=user_data['email'],
                        address=user_data['address'],
                        zipcode=user_data['zipcode'],
                        country=user_data['country'],
                        state=user_data['state'],
                        birthday=birthday
                    )


                    # store user in database
                    storage.new(new_user)
                    storage.save()

                     # Now, obtain the user ID after the user has been added to the database
                    new_user = storage.find_user_by_email(user_data['email'])
                    # Create a new family instance and associate it with the user
                    new_family = Family(name=family_name, owner_id=new_user.id)

                    new_user.family = new_family

                    # Store the updated user in the database with the associated family
                    storage.save()

                    flash('Registration successful', category='success')
                    return redirect(url_for('auth.login'))
            else:
                family_id = request.form.get('family_id')

                if not family_id:
                    flash('Please select an existing family to join', category='error')
                    return render_template('auth/register.html', user_data=user_data)  # Display the registration form again
                
                if all(user_data[field] for field in ['firstname', 'lastname', 'password', 'confirm_pass', 'email', 'address', 'zipcode', 'country', 'state', 'birth_month', 'birth_day']):
                    # All checks passed, proceed with registration
                    birthday = f"{user_data['birth_month']}/{user_data['birth_day']}"
                    new_user = User(
                        firstname=user_data['firstname'],
                        lastname=user_data['lastname'],
                        username=user_data['username'],
                        password=user_data['password'],
                        email=user_data['email'],
                        address=user_data['address'],
                        zipcode=user_data['zipcode'],
                        country=user_data['country'],
                        state=user_data['state'],
                        birthday=birthday
                    )

                    # Query the database to get the selected family
                    selected_family = storage.get_family_by_id(family_id)
                    if selected_family:
                        
                        # Associate the user with the selected family
                        new_user.family = selected_family
                        # Store user with the associated family in the database
                        storage.new(new_user)
                        storage.save()
                        message = f"You have successfully registered and joined {selected_family.name}'s Family"
                        flash(message, category='success')
                        return redirect(url_for('auth.login'))
                    else:
                         # Handle the case where the selected family doesn't exist
                        flash('The selected family does not exist', category='error')
                        return render_template('auth/register.html', user_data=user_data)  # Display the registration form again
        
        return render_template('auth/register.html', user_data=user_data)
    
    return render_template('auth/register.html')

@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

web_flask/views.py
from flask import Blueprint, render_template, url_for, request, flash, redirect, jsonify, current_app
from flask_login import login_required, current_user
from models import storage
from models.task import Task
from models.notification import Notification
import json, uuid, os
from datetime import datetime
from .functions import inject_globals, allowed_file

views = Blueprint('views', __name__)
@views.context_processor
def inject_global():
    return inject_globals()

# Define a sample route that uses the family_tasks variable
"""Route to Landing PAGE"""
@views.route('/')
def landing_page():
    background_image_urls = [
        url_for('static', filename='images/home1.jpg'),
        url_for('static', filename='images/home2.jpg'),
        url_for('static', filename='images/home3.jpg')
    ]
    return render_template('landing_page.html', images = background_image_urls)

@views.route('/dashboard')
@login_required
def dashboard():
    # Assuming you have a datetime field named 'created_at' in your Task model
    user = current_user
    tasks = storage.get_task(user.family_id)
    recent_tasks = tasks

    return render_template('dashboard.html', user=user, recent_tasks=recent_tasks)

@views.route('/users')
@login_required
def users():
    return render_template('users.html', user = current_user)

@views.route('/tasks', methods=['GET', 'POST'])
@login_required
def tasks():
    if request.method == 'POST':
        # Process the form submission
        task_title = request.form.get('task_title')
        description = request.form.get('description')
        priority = request.form.get('priority')
        due_date = request.form.get('due_date')
        user_id = current_user.id
        family_id = current_user.family_id
        status = request.form.get('status')
        if status:
            status = 1
        else:
            status = 0
        if priority == 'High':
            priority = 2
        elif priority == 'Medium':
            priority = 1
        else:
            priority = 0

        if len(description) < 5:
            flash('please give more detailed description', category='error')
        elif len(task_title) < 2:
            flash('detailed title is required', category='error')
        elif len(due_date) < 1:
            flash('please set due date', category='error')
        else:
            new_task = Task(title=task_title, description=description, due_date=due_date, user_id=user_id, family_id=family_id, status = status)
            storage.new(new_task)
            storage.save()

            # Get all family members (excluding the creator)
            family_members = storage.get_all_families(new_task.family_id)
            for member in family_members:
                # print(member.firstname)
                if member.id != new_task.user_id:  # Exclude the creator
                    content = f"A new task '{new_task.title}' has been created in your family."
                    notification = Notification(
                        sender=current_user,
                        recipient=member,  # Use the member's ID as the recipient
                        content=content,
                        family_id=new_task.family_id
                    )
                    storage.new(notification)

            storage.save()
                        


            flash('New Task added Successfully', category='success')
            return redirect(url_for('views.tasks'))
    family_tasks = current_user.family.tasks
    return render_template('task.html', user = current_user, family_tasks=family_tasks)

@views.route('/notification')
@login_required
def notification():
    
    return render_template('notification.html', user = current_user)

@views.route('/events')
@login_required
def events():
    return render_template('events.html', user = current_user)

@views.route('/family')
@login_required
def family():
    
    return render_template('family.html', user = current_user)

@views.route('/settings')
@login_required
def settings():
    
    return render_template('settings.html', user = current_user)

@views.route('/delete-task', methods=['POST'])
def delete_task():
    data = json.loads(request.data)
    taskId = data['taskId']
    task = storage.get_task_by_id(taskId)

    if not task:
        return jsonify({'error': 'Task not found'}), 404
    else:
        if task.user_id == current_user.id:
            # Delete the task from the database (you should have a method for this)
            storage.delete(task)
            storage.save()

            # Return a success message
            flash('Task Deleted Successfully', category='success')
            return jsonify({'message': 'Task deleted successfully'}), 200

@views.route('/update-task/<string:task_id>', methods=['GET', 'POST'])
def update_task(task_id):
    # Fetch the task from the database based on task_id
    task = storage.get_task_by_id(task_id)
    
    if not task:
        # Handle the case where the task doesn't exist or an error occurs
        # You can return an error message or appropriate status code
        flash("Task not found or error fetching task", category='error')
        return redirect(url_for('views.tasks'))
    
    if request.method == 'POST':
        # Retrieve form data from the POST request
        task_title = request.form.get('task_title')
        description = request.form.get('description')
        priority = request.form.get('priority')
        due_date = request.form.get('due_date')
        status = request.form.get('status')
        
        # Convert the 'status' value to an integer
        if status:
            status = 1
        else:
            status = 0

        if priority == 'High':
            priority = 2
        elif priority == 'Medium':
            priority = 1
        else:
            priority = 0

        # Update task attributes
        task.title = task_title
        task.description = description
        task.priority = priority
        task.due_date = due_date
        task.status = status
        task.updated_at = datetime.utcnow()
        
        # Save the updated task
        storage.update(task)
        flash('Task updated Successfully', category='success')
    
    # If the request is a GET request (e.g., to fetch task data for AJAX update)
    task_data = {
        'title': task.title,
        'description': task.description,
        'priority': task.priority,
        'due_date': task.due_date,
        'status': task.status,
        'id': task.id
        # Add other task attributes here
    }
    
    return jsonify(task_data)

@views.route("/uploads", methods=["POST"])
def uploads():
    if request.method == "POST" and "photo" in request.files:
        photo = request.files["photo"]
        if photo and allowed_file(photo.filename):
            # Generate a unique filename
            unique_filename = str(uuid.uuid4())[:8] + os.path.splitext(photo.filename)[-1]

            # Save the uploaded file with the unique filename
            file_path = current_app.config["UPLOADED_PHOTOS_DEST"]
            if not os.path.exists(file_path):
                os.makedirs(file_path)
            photo_path = os.path.join(file_path, unique_filename)
            photo.save(photo_path)

            # Save the filename in the database
            user_id = current_user.id
            user = storage.find_user_by_id(user_id)  # Retrieve the user by ID
            if user:
                user.profile_img = unique_filename  # Update the profile_img field
                storage.save()  # Commit changes
                flash('Image successfully uploaded', category='success')
                return redirect(url_for('views.settings'))
        else:
            flash('Image type not allowed', category='error')
    return redirect(url_for('views.settings'))

web_flask/templates/_messages.html
{% with messages = get_flashed_messages(with_categories = true) %}
    {% if messages %}
        {% for category, message in messages %}
            {% if category == 'success' %}
                <div class="ui success message">
                    <i class="close icon"></i>
                    <div class="header">
                    {{ message }}
                    </div>
                    <!-- <p>You may now log-in with the username you have chosen</p> -->
                </div>
            {% else %}
                <div class="ui negative message">
                    <i class="close icon"></i>
                    <div class="header">
                    {{ message }}
                    </div>
                    <!-- <p>That offer has expired</p> -->
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endwith %}

web_flask/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/base.css')  }}">
    {% block task_css %}{% endblock %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.5.0/semantic.min.css"
        integrity="sha512-KXol4x3sVoO+8ZsWPFI/r5KBVB/ssCGB5tsv2nVOKwLg33wTFP3fmnXa47FdSVIshVTgsYk/1734xSk9aFIa4A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />    
    <link rel="stylesheet" href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css">
    <title>{% block title %}Base{% endblock %}</title>
</head>
<body>
    <div class="sidebar">
        <div class="logo_details">
            <i class="bx bxl-audible zone"></i>
            <div class="logo_name">FAMEC</div>
            <i class="bx bx-menu" id="btn"></i>
        </div>
        <ul class="nav-list">
            <li>
                <i class="bx bx-search"></i>
                <input type="text" placeholder="Search...">
                <span class="tooltip">Search</span>
            </li>
            <li>
                <a href="{{ url_for('views.dashboard') }}">
                    <i class="bx bx-grid-alt"></i>
                    <span class="link_name">Dashboard</span>
                </a>
                <span class="tooltip">Dashboard</span>
            </li>
            <li>
                <a href="{{ url_for('views.users') }}">
                    <i class="bx bx-user"></i>
                    <span class="link_name">User</span>
                </a>
                <span class="tooltip">User</span>
            </li>
            <li>
                <a href="#">
                    <i class="bx bx-chat"></i>
                    <span class="link_name">Notes</span>
                </a>
                <span class="tooltip">Notes</span>
            </li>
            <li>
                <a href="{{ url_for('views.tasks') }}">
                    <i class='bx bx-task'></i>
                    <span class="link_name">Tasks</span>
                </a>
                <span class="tooltip">Tasks</span>
            </li>
            <li>
                <a href="{{ url_for('views.notification') }}">
                    <i class='bx bx-bell' ></i>
                    <span class="link_name">Notification</span>
                </a>
                <span class="tooltip">Notification</span>
            </li>
            <li>
                <a href="{{ url_for('views.events') }}">
                    <i class='bx bx-calendar-event'></i>
                    <span class="link_name">Event</span>
                </a>
                <span class="tooltip">Event</span>
            </li>
            <li>
                <a href="{{ url_for('views.family') }}">
                    <i class='bx bx-group' ></i>
                    <span class="link_name">Family</span>
                </a>
                <span class="tooltip">Family</span>
            </li>
            <li>
                <a href="{{ url_for('views.settings') }}">
                    <i class="bx bx-cog"></i>
                    <span class="link_name">Settings</span>
                </a>
                <span class="tooltip">Setting</span>
            </li>
            <li class="profile">
                <div class="profile_details">
                    <img src="{{ url_for('static', filename='images/avatar.png') }}" alt="profile image">
                    <div class="profile_content">
                        <div class="name">
                            {% if user.is_authenticated %}
                                {{ user.username }}
                            {% endif %}
                        </div>
                        <div class="designation">Admin</div>
                    </div>
                </div>
                <!-- <i class="bx bx-log-out" id="log_out"></i> -->
                <a class="" href="{{ url_for('auth.logout') }} "id='log_out' >
                    <i class="bx bx-log-out" id="log_out"></i>
                </a>
            </li>
        </ul>
    </div>
    <section class="home-section">
        <div class="pusher">
            <div class="ui menu borderless" style="background-color: #ff91a4;">
                <a class="item custom-fonts">{% block section_title %}{% endblock %}</a>
                {% include '_messages.html' %}
                <div class="right menu">
                    <div class="item mobile-view">
                        <a class="item notification-item" href="{{ url_for('views.notification') }}">
                            <i class="icon bell"></i>
                            {% if notification_counter > 0 %}
                            <div class="floating ui circular red label">{{ notification_counter }}</div>
                            {% endif %}
                        </a>
                        <a class="item task-item"  href="{{ url_for('views.tasks') }}">
                            <i class='bx bx-task'></i> Tasks
                            {% if task_counter > 0 %}
                            <div class="floating ui circular teal label">{{ task_counter }}</div>
                            {% endif %}
                        </a>
                    </div>
                    <div class="ui dropdown item custom-style">
                        <img class="ui avatar image" src="{{ url_for('static', filename='images/avatar.png')  }}">
                        <span class="text profile-text"> <!-- Add a text class for mobile -->
                            {% if user.is_authenticated %}
                                {{ user.firstname }}
                            {% endif %}
                        </span>
                        <i class="dropdown icon" style="margin-left: 3px;"></i>
                        <div class="menu">
                            <a class="item" href="{{ url_for('views.notification') }}">
                            <i class="icon mail"></i> Notification
                            </a>
                            <a class="item" href="{{ url_for('views.settings') }}">
                                <i class="icon setting"></i> Settings
                            </a>
                            <a class="item" href="{{ url_for('auth.logout') }}">
                                <i class="icon logout"></i> Logout
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section>
        <div class="ui fluid container">
            {% block page_contents %}{% endblock %}
        </div>
    </section>
    <div class="ui inverted vertical footer segment">
        <div class="ui container very padded basic segment">
        <div class="ui stackable inverted divided equal height stackable grid">
            <div class="three wide column">
            <h4 class="ui inverted header">About</h4>
            <div class="ui inverted link list">
                <a href="{{ url_for('views.landing_page') }}" class="item">Contact Us</a>
            </div>
            </div>
            <div class="three wide column">
            <h4 class="ui inverted header">Services</h4>
            <div class="ui inverted link list">
                <a href="#" class="item">Blog</a>
                <a href="#" class="item">Famec FAQ</a>
                <a href="#" class="item">Emergency Contact</a>
            </div>
            </div>
            <div class="seven wide column">
            <h4 class="ui inverted header">Footer Header</h4>
            <p class="ui inverted grey text">Copyright © 2023 Your Company Name. All rights reserved.</p>
            </div>
        </div><br>
        <p style="text-align: center;"><strong style="color: #fff;">FAMEC © 2023. All rights reserved.</strong></p>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.5.0/semantic.min.js"></script>
    <script src="{{ url_for('static', filename='scripts/base.js')  }}"></script>
    {% block task_script %}{% endblock %}
    {% block settings_script %}{% endblock %}
</body>
</html>

web_flask/templates/events.html
{% extends "base.html" %}{% block title %}Events{% endblock %}
{% block section_title %}Events{% endblock %}

{% block page_contents %}

{% endblock %}

web_flask/templates/family.html
{% extends "base.html" %}{% block title %}Family{% endblock %}
{% block section_title %}Family{% endblock %}

{% block page_contents %}
  <!-- Page Contents -->
    <div class="ui fluid padded container segment">
        <div class="ui yellow message">
          <i class="star icon"></i>
          To make the entire content of an item link, check out the link variation below
        </div>
        {% for family in user.family.members %}
        <div class="ui items">
          <div class="item">
            <a class="ui tiny image">
              <img src="{{ url_for('static', filename='uploads/' + family.profile_img) }}">
            </a>
            <div class="content">
              <a class="header">{{ family.firstname|capitalize + ' ' + family.lastname|capitalize }}</a>
              <div class="description">
                <p>Veronika Ossi is a set designer living in New York who <a>enjoys</a> kittens, music, and partying.</p>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

web_flask/templates/settings.html
{% extends "base.html" %}{% block title %}Settings{% endblock %}
{% block section_title %}Profile{% endblock %}

{% block page_contents %}
  <!-- Page Contents -->
  <div class="ui fluid container segment">
    <h2 class="ui dividing header">Family Information</h2>
    <form class="ui form">
        <div class="field">
            <label>Family Name</label>
            <input type="text" name="shipping[first-name]" value="{{ user.family.name }}">
        </div>
        <div class="field">
            <label>Family ID</label>
            <input type="text" name="shipping[first-name]" value="{{ user.family.owner_id }}" readonly>
        </div>
    </form>
    <h2 class="ui header">User Information</h2>
    <h4 class="ui header">Profile image</h4>
    <div class="ui special cards">
        <div class="card">
            <div class="blurring dimmable image">
                <div class="ui dimmer">
                <div class="content">
                    <div class="center">
                        <div class="ui inverted button" id="upload-image">Update Image</div>
                    </div>
                </div>
                </div>
                <img src="{{ url_for('static', filename='uploads/' + profile_image) }}">
            </div>
            <div class="content">
                <a class="header">{{ user.firstname|capitalize + ' ' + user.lastname|capitalize }}</a>
                <div class="meta">
                <span class="date">Joined in {{ user.created_at.strftime('%B %d, %Y') }}</span>
                </div>
            </div>
            <div class="extra content">
                <a>
                <i class="users icon"></i>
                2 Members
                </a>
            </div>
        </div>
    </div>
    <br><br>
    <form class="ui form">
        <div class="field">
            <label>Name</label>
            <div class="two fields">
                <div class="field">
                <input type="text" name="shipping[first-name]" placeholder="First Name" value="{{ user.firstname }}">
                </div>
                <div class="field">
                <input type="text" name="shipping[last-name]" placeholder="Last Name" value="{{ user.lastname }}">
                </div>
            </div>
        </div>
        <div class="field">
            <label>Address</label>
            <div class="fields">
                <div class="twelve wide field">
                <input type="text" name="shipping[address]" placeholder="Street Address" value="{{ user.address }}">
                </div>
                <div class="four wide field">
                <input type="text" name="shipping[address-2]" placeholder="Apt #">
                </div>
            </div>
        </div>
        <div class="two fields">
            <div class="field">
                <label>State</label>
                <input type="text" name="shipping[last-name]" placeholder="State" value="{{ user.state }}">
            </div>
            <div class="field">
                <label>Country</label>
                <input type="text" name="shipping[last-name]" placeholder="Country" value="{{ user.country }}">
            </div>
        </div>
        <div class="ui button" tabindex="0">Submit Changes</div>
    </form>
  </div>

<!-- upload image modal -->
<div class="ui mini modal upload-image">
    <div class="header">Upload Profile Picture</div>
    <div class="content">
        <form class="ui form" method="POST" enctype="multipart/form-data" action="{{ url_for('views.uploads') }}">
            <div class="field">
                <label>select image</label>
                <input type="file" name="photo"  class="image-upload" accept="image/*" />
            </div>
        </div>
        <div class="actions">
            <button class="ui positive button" type="submit">Upload</button>
            <div class="ui negative button">Cancel</div>
        </div>
    </form>
</div>
{% endblock %}
{% block settings_script %}
    <script src="{{ url_for('static', filename='scripts/settings.js')  }}"></script>
{% endblock %}

web_flask/templates/users.html
{% extends "base.html" %}{% block title %}users{% endblock %}
{% block section_contents %}
    <div class="text">Users</div>
{% endblock %}